    //src/constants/shareBackgrounds.ts
    export const GRADIENT_PRESETS = [
        { id: "slate", from: "#f8fafc", to: "#e5e7eb" },
        { id: "sky", from: "#e0f2fe", to: "#bae6fd" },
        { id: "lavender", from: "#ede9fe", to: "#ddd6fe" },
        { id: "mint", from: "#ecfeff", to: "#cffafe" },
        { id: "sand", from: "#fffbeb", to: "#fef3c7" },
        { id: "rose", from: "#fff1f2", to: "#ffe4e6" },
    ];

    export const NATURE_BACKGROUNDS = [
        { id: "1", name: "Mountain Sunrise", url: "/verse-bg/mountain-sunrise.png" },
        { id: "2", name: "Ocean Waves", url: "/verse-bg/ocean-waves.png" },
        { id: "3", name: "Forest Path", url: "/verse-bg/forest-path.png" },
        { id: "4", name: "Desert Dunes", url: "/verse-bg/desert-dunes.png" },
        { id: "5", name: "Mountain Lake", url: "/verse-bg/mountain-lake.png" },
        { id: "6", name: "Sunset Fields", url: "/verse-bg/sunset-fields.png" },
        { id: "7", name: "Coastal Cliffs", url: "/verse-bg/coastal-cliffs.png" },
        { id: "8", name: "Autumn Forest", url: "/verse-bg/autumn-forest.png" },
        { id: "9", name: "Mountain Peak", url: "/verse-bg/mountain-peak.png" },
        { id: "10", name: "Peaceful Meadow", url: "/verse-bg/peaceful-meadow.png" },
        { id: "11", name: "Bible Cross", url: "/verse-bg/bible-cross.png" },
        { id: "12", name: "Blurry Grass", url: "/verse-bg/blurry-grass.png" },
        { id: "13", name: "Blurry River", url: "/verse-bg/blurry-river.png" },
        { id: "14", name: "Calm Horizon Light", url: "/verse-bg/calm-horizon-light.png" },
        { id: "15", name: "Coastal View", url: "/verse-bg/coastal-view.png" },
        { id: "16", name: "Desert Cross (Dark)", url: "/verse-bg/dark-desert-distant-cross.png" },
        { id: "17", name: "Light Gradient Cross", url: "/verse-bg/light-gradient-negative-cross.png" },
        { id: "18", name: "Old Bible", url: "/verse-bg/old-bible.png" },
        { id: "19", name: "Open Bible (Top View)", url: "/verse-bg/openbible-top.png" },
        { id: "21", name: "Soft Forest Light Rays", url: "/verse-bg/soft-forest-light-rays.png" },
        { id: "22", name: "Implied Light Cross", url: "/verse-bg/soft-light-implied-cross.png" },
        { id: "24", name: "Flowers 1", url: "/verse-bg/flowers-1.png" },
        { id: "25", name: "Flowers 2", url: "/verse-bg/flowers-2.png" },
        { id: "26", name: "Flowers 3", url: "/verse-bg/flowers-3.png" },
        { id: "27", name: "Flowers 4", url: "/verse-bg/flowers-4.png" },
        { id: "28", name: "Flowers 5", url: "/verse-bg/flowers-5.png" },
        { id: "29", name: "Flowers 6", url: "/verse-bg/flowers-6.png" },
        { id: "30", name: "Flowers 7", url: "/verse-bg/flowers-7.png" },
        { id: "31", name: "Flowers 8", url: "/verse-bg/flowers-8.png" },
        { id: "32", name: "Flowers 9", url: "/verse-bg/flowers-9.png" },
        { id: "33", name: "Flowers 10", url: "/verse-bg/flowers-10.png" },
        { id: "34", name: "Flowers 11", url: "/verse-bg/flowers-11.png" },
        { id: "35", name: "river-1", url: "/verse-bg/river-1.png" },
        { id: "36", name: "river-2", url: "/verse-bg/river-2.png" },
        { id: "37", name: "foggy-river", url: "/verse-bg/foggy-river.png" },
        { id: "38", name: "dandelions", url: "/verse-bg/dandelions.png" },
    ];
